USE EMPRESA_VETERINARIA;

SELECT COUNT(*)
FROM ANIMAL;

SELECT COUNT(*)
FROM VACINA;

SELECT 
	TIPO.TIPO_ANIMAL AS CATEGORIA,
	COUNT(ANIMAL.ID)
FROM ANIMAL
INNER JOIN TIPO_ANIMAL AS TIPO 
ON ANIMAL.ID_TIPO_ANIMAL = TIPO.ID
GROUP BY CATEGORIA;
