USE EMPRESA_VETERINARIA;

-- A) QUAL A QUANTIDADE DE ANIMAIS REGISTRADAS NO SISTEMA?
SELECT COUNT(*)
FROM ANIMAL;

-- B) QUAL O TOTAL DE VACINAS APLICADAS REGISTRADAS NO SISTEMA?
SELECT COUNT(*)
FROM VACINA;

-- C) QUANTOS ANIMAIS TEMOS AGRUPADOS REGISTRADOS PARA CADA CATEGORIA?
SELECT 
	TIPO.TIPO_ANIMAL AS CATEGORIA,
	COUNT(ANIMAL.ID)
FROM ANIMAL
INNER JOIN TIPO_ANIMAL AS TIPO 
ON ANIMAL.ID_TIPO_ANIMAL = TIPO.ID
GROUP BY CATEGORIA;

-- D) QUAL A CATEGORIA DE ANIMAIS QUE MAIS VACINAS RECEBEU?
SELECT 
	VACINA.ID_ANIMAL,
    TIPO_ANIMAL.TIPO_ANIMAL,
    COUNT(VACINA.NOME)
    
FROM VACINA
INNER JOIN ANIMAL
ON VACINA.ID_ANIMAL = ANIMAL.ID
INNER JOIN TIPO_ANIMAL
ON ANIMAL.ID_TIPO_ANIMAL = TIPO_ANIMAL.ID
GROUP BY ID_ANIMAL
ORDER BY COUNT(VACINA.NOME) DESC;
