USE EMPRESA_VETERINARIA;

SELECT COUNT(*)
FROM ANIMAL;

SELECT COUNT(*)
FROM VACINA;

SELECT 
	TIPO.TIPO_ANIMAL AS CATEGORIA,
	COUNT(ANIMAL.ID)
FROM ANIMAL
INNER JOIN TIPO_ANIMAL AS TIPO 
ON ANIMAL.ID_TIPO_ANIMAL = TIPO.ID
GROUP BY CATEGORIA;

SELECT 
	VACINA.ID_ANIMAL,
    TIPO_ANIMAL.TIPO_ANIMAL,
    COUNT(VACINA.NOME)
    
FROM VACINA
INNER JOIN ANIMAL
ON VACINA.ID_ANIMAL = ANIMAL.ID
INNER JOIN TIPO_ANIMAL
ON ANIMAL.ID_TIPO_ANIMAL = TIPO_ANIMAL.ID
GROUP BY ID_ANIMAL
ORDER BY COUNT(VACINA.NOME) DESC;
