USE NOTA_FISCAL_NORMALIZADA;

-- FORMA CLÁSSICA DE CONSULTAS COMBINADAS

SELECT NOTA_FISCAL.*, ITEM_NOTA_FISCAL.*
FROM NOTA_FISCAL, ITEM_NOTA_FISCAL
WHERE NOTA_FISCAL.NRO_NOTA = ITEM_NOTA_FISCAL.NRO_NOTA;

-- PODEMOS DEFINIR ALIAS (APELIDOS) PARA AS TABELAS E FACILITAR A CODIFICAÇÃO COM O "AS"

SELECT NF. *, INF. *
FROM NOTA_FISCAL AS NF, ITEM_NOTA_FISCAL AS INF
WHERE NOTA_FISCAL.NRO_NOTA = ITEM_NOTA_FISCAL.NRO_NOTA;

-- AQUI NESSE SELECT ESTOU SELECIONANDO AS COLUNAS ESPECÍFICAS DE CADA TABELA (NF= NOTA FISCAL E INF = ITEM NOTA FISCAL)
SELECT NF.NRO_NOTA, NF.DT_EMISSAO, NF.VL_TOTAL,
	   INF.COD_PRODUTO, P.DESC_PRODUTO, P.UN_MED, 
       INF.QTD_PRODUTO, INF.VL_PRECO, 
       INF.VL_TOTAL
-- INDICO O ALIAS (APELIDOS DAS TABELAS) PARA DIMINUIR A ESCRITA
FROM NOTA_FISCAL AS NF,
	ITEM_NOTA_FISCAL AS INF,
    PRODUTO AS P

-- EU PASSO O PARÂMETRO QUE EU QUERO QUE ELE BUSQUE, COMO SE FOSSE UM FILTRO
WHERE
	NF.NRO_NOTA = INF.NRO_NOTA
    AND INF.COD_PRODUTO = P.COD_PRODUTO
    
-- E POR FIM EU ORDENO OS ITENS PELO NÚMERO DA NOTA E COD_PRODUTO, DE FORMA DESCENDENTE E ASCENDENTE, RESPECTIVAMENTE
ORDER BY 
NF.NRO_NOTA DESC, INF.COD_PRODUTO ASC;

SELECT NF. *, INF. *
FROM NOTA_FISCAL AS NF, ITEM_NOTA_FISCAL AS INF
WHERE NOTA_FISCAL.NRO_NOTA = ITEM_NOTA_FISCAL.NRO_NOTA;

-- INNER JOIN
SELECT NF.NRO_NOTA, NF.DT_EMISSAO, NF.VL_TOTAL,
	   INF.COD_PRODUTO, P.DESC_PRODUTO, P.UN_MED, 
       INF.QTD_PRODUTO, INF.VL_PRECO, 
       INF.VL_TOTAL

-- AMARRA AS TRÊS TABELAS PARA RETORNAR APENAS O QUE TIVER PREENCHIDO NAS TRÊS
FROM NOTA_FISCAL AS NF
	INNER JOIN
			ITEM_NOTA_FISCAL AS INF ON NF.NRO_NOTA = INF.NRO_NOTA
	INNER JOIN
			PRODUTO AS P ON INF.COD_PRODUTO = P.COD_PRODUTO
	WHERE NF.NRO_NOTA = 4
ORDER BY 
NF.NRO_NOTA DESC, INF.COD_PRODUTO ASC;

-- FUNÇÕES DE AGREGAÇÃO 
-- CONTANDO E QUANTIFICANDO REGISTROS 

-- QUANTAS NOTAS FISCAIS TEM EMITIDAS?
SELECT COUNT(*)
FROM NOTA_FISCAL; 

-- NOTAS FISCAIS POR PERÍODO
SELECT COUNT(*)
FROM NOTA_FISCAL
WHERE DT_EMISSAO BETWEEN '2025-03-21' AND 2025-03-25;

-- TOTAL DE NOTAS DO ANO
SELECT COUNT(*)
FROM NOTA_FISCAL
WHERE YEAR(DT_EMISSAO = 2025);

SELECT N FROM NOTA_FISCAL.n;

-- MAX() - OBTENDO O CLIENTE QUE MAIS COMPROU DETERMINADO PRODUTO EM UMA ÚNICA NOTA FISCAL

SELECT 
	NF.NM_CLIENTE AS CLIENTE,
    P.DESC_PRODUTO AS PRODUTO,
    MAX(QTD_PRODUTO) AS QTD
FROM ITEM_NOTA_FISCAL AS INF
INNER JOIN NOTA_FISCAL AS NF 
ON INF.NRO_NOTA = NF.NRO_NOTA
INNER JOIN PRODUTO AS P
ON INF.COD_PRODUTO = P.COD_PRODUTO
WHERE INF.COD_PRODUTO = 2
GROUP BY NF.NM_CLIENTE, P.DESC_PRODUTO
ORDER BY CLIENTE, QTD DESC;
