CREATE DATABASE EMPRESA_VETERINARIA;

USE EMPRESA_VETERINARIA;

CREATE TABLE TIPO_ANIMAL (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TIPO_ANIMAL VARCHAR(100) NOT NULL
);

CREATE TABLE ANIMAL (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_TIPO_ANIMAL INT NOT NULL,
	CONSTRAINT FK_TIPO_ANIMAL_ANIMAL
        FOREIGN KEY (ID_TIPO_ANIMAL)
        REFERENCES TIPO_ANIMAL(ID),
	DATA_NASCIMENTO DATETIME NOT NULL,
    COR VARCHAR(50) NOT NULL,
    PESO FLOAT NOT NULL,
    ALTURA FLOAT NOT NULL
);

CREATE TABLE VACINA (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_APLICACAO DATETIME NOT NULL,
    ID_ANIMAL INT NOT NULL,
    CONSTRAINT FK_ID_ANIMAL_VACINA
		FOREIGN KEY (ID_ANIMAL)
        REFERENCES TIPO_ANIMAL(ID)
);

ALTER TABLE VACINA
ADD FOREIGN KEY (ID_ANIMAL)
REFERENCES ANIMAL(ID);